### ISSUE TITLE
Mines endpoint limit query parameter

### ISSUE THREAD

**Issue by proletariatpatryk** [Alien-Worlds/alienworlds-api#1]
I've found that setting the query parameter of limit to 2 will result in this error.

`{
    "statusCode": 500,
    "error": "Internal Server Error",
    "message": "Limit maximum is 5000"
}`

I've tried a limit value of 0,1,3, and 4 and they all have worked no problem.

**Comment by Kolechko123** [comment]
more details on how to run the script
